Handle missing MIME types in MediaTypeFinder
It's possible for a response not to have a MIME type (mimetype=None).
Previously, this would result in an exception from within fnmatch():

  TypeError: expected str, bytes or os.PathLike object, not NoneType

This change guards against that condition and raises MediaTypeNotFound
instead. Tests have also been added for this module.